---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.7
  - name: centos-7.2


suites:
  - name: rhel-agent
    run_list:
      - role[rhel-ossec-agent]
    excludes: ["ubuntu-14.04"]
    attributes:
  - name: rhel-server
    run_list:
      - role[rhel-ossec-server]
    excludes: ["ubuntu-14.04"]
    attributes: