---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: packer-centos-7.1
    driver:
      box: packer-centos-7.1
      vm_hostname: dev-centos-71.neustar.com


suites:
  - name: default
    run_list:
      - recipe[autossec::default]
    attributes:
  - name: server
    run_list:
      - recipe[autossec::server]
    attributes: