---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[autossec::default]
    attributes:
  - name: server
    run_list:
      - recipe[autossec::server]
    attributes: